### PR TITLE
Add support for newer XCF files up to version 12

### PR DESCRIPTION
**Pull request by dolda2000**
GIMP 2.10 added rather fundamental changes to the XCF file format, perhaps most importantly variable-sized pointers to support files larger than 4 GB, but also a precision value for the pixel format. This attempts to add support for those features.

### CODE REVIEW

**Comment by dolda2000** [comment]
Also, note that, while the precision value is read so that the structure offsets are preserved, it is not actually used. Pixel operations on other than gamma-encoded byte values probably don't produce correct results.

**Comment by j-jorge** [comment]
Thanks for the PR. It looks good to me, maybe could you add some tests in the dotest script using XCF files in the newest format?

**Comment by dolda2000** [comment]
>maybe could you add some tests in the dotest script using XCF files in the newest format?
Sure. I've added two simple tests for Zlib pixel compression and 64-bit XCF pointers. Not sure if I can think of anything else meaningful to test for.

**Comment by dolda2000** [comment]
By the way, the support for Zlib compression added a direct dependency on libz that wasn't there previously. I figured it probably doesn't matter since xcftools already depends on libz indirectly via libpng, but technically the development files for libz didn't previously need to be installed to compile xcftools, so I figured I should at least mention it.

**Comment by j-jorge** [comment]
> By the way, the support for Zlib compression added a direct dependency on libz that wasn't there previously. I figured it probably doesn't matter since xcftools already depends on libz indirectly via libpng, but technically the development files for libz didn't previously need to be installed to compile xcftools, so I figured I should at least mention it.

Seems perfectly reasonable to me :)

**Comment by j-jorge** [comment]
Thanks for this neat PR :)

**Comment by dolda2000** [comment]
Thanks for merging it! :)

**Pull request merged**
